# Copyright (c) 2023-∞ blurryroots innovation qanat OÜ

# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  commands:
    - echo "Making sure system is setup accordingly ..."
    - apt-get update -y --fix-missing
    - apt-get install -y -q python3 python3-pip python3.8-venv make doxygen
    - apt-get install -y -q bash
    - echo "Setting default shell ..."
    - chsh -s /bin/bash
    - echo "Chaning shell ..."
    - /bin/bash
    - echo "Install dependencies ..."
    - make pip-update-all
    - echo "Building documentation using doxygen ..."
    - make docs-build
    - mv docs/published "$READTHEDOCS_OUTPUT/html"
