#!env python3
"""    
    CLI tool to generate files from templates.

    2023-∞ (c) blurryroots innovation qanat OÜ. All rights reserved.
    See license.md for details.

    https://think-biq.com
"""
import sys
from src.tools.tmplr import main as tmplr_main


if '__main__' == __name__:
    """! Local execution script shorthand."""
    # Call CLI entry function.
    r = tmplr_main ()
    # Exit with return code.
    sys.exit (r)
